# Generated by Django 4.1.7 on 2023-03-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_department_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
